### ISSUE TITLE
Please add option to use certificates for authentication

### ISSUE THREAD

**Issue by artisticcheese** [Mimeo/cAzureKeyVault#4]
Please add option to authenticate with certificate instead of username/password for service principal

**Comment by nshenoy** [comment]
That's interesting. I can see how this could be useful. Would you like to give it a shot and open a PR?

**Comment by artisticcheese** [comment]
I'm not very well versed with Git so pardon my ignorance. I will create PR and instead will do MSI based access, this will be actually much simpler. Your module depends on AzureRM modules installed on system, need to add it to definition as well.
